-- question 1
-- 1.Show the percentage of wins of each bidder in the order of highest to lowest percentage.

select IPL_BIDDER_DETAILS.BIDDER_ID,IPL_BIDDER_DETAILS.BIDDER_NAME,
(select count(BIDDER_ID) from IPL_BIDDING_DETAILS
where IPL_BIDDING_DETAILS.bid_status='won' and IPL_BIDDING_DETAILS.bidder_id= IPL_BIDDER_DETAILS.bidder_id )/
(select NO_OF_BIDS from IPL_BIDDER_POINTS where IPL_BIDDER_DETAILS.bidder_id=IPL_BIDDER_POINTS.bidder_id)*100 as WIN_PERCENTAGE
from IPL_BIDDER_DETAILS order by WIN_PERCENTAGE desc; -- 30 ROWS
 
-- 2.	Display the number of matches conducted at each stadium with stadium name, city from the database. 

select IPL_STADIUM.STADIUM_ID,STADIUM_NAME,CITY, count(IPL_MATCH_SCHEDULE.STADIUM_ID) as TOTAL_MATCHES
from IPL_STADIUM
join IPL_MATCH_SCHEDULE using (STADIUM_ID) group by STADIUM_ID order by STADIUM_ID;
 
-- 3.  in a given stadium, what is the percentage of wins by a team which has won the toss?

select IPL_STADIUM.STADIUM_ID,STADIUM_NAME,CITY,
(SELECT COUNT(*) FROM IPL_MATCH JOIN IPL_MATCH_SCHEDULE ON IPL_MATCH_SCHEDULE.MATCH_ID=IPL_MATCH.MATCH_ID 
WHERE TOSS_WINNER=MATCH_WINNER and IPL_MATCH_SCHEDULE.STADIUM_ID=IPL_STADIUM.STADIUM_ID)/
(SELECT COUNT(*) from IPL_MATCH_SCHEDULE where IPL_MATCH_SCHEDULE.stadium_id = IPL_STADIUM.stadium_id)*100 AS WIN_PERCENTAGE
from IPL_STADIUM;


-- 4.	Show the total bids along with bid team and team name.
SELECT BID_TEAM,IPL_TEAM.TEAM_NAME,COUNT(BID_TEAM) as count_bid
FROM IPL_BIDDING_DETAILS 
JOIN IPL_TEAM 
ON IPL_TEAM.TEAM_ID=IPL_BIDDING_DETAILS.BID_TEAM
GROUP BY IPL_BIDDING_DETAILS.BID_TEAM
ORDER BY IPL_BIDDING_DETAILS.BID_TEAM ;

-- 5.	Show the team id who won the match as per the win details.

# BELOW CODE ONLY DISPLAY TEAM ID OF MATCH WINNER 
SELECT MATCH_ID, if(IPL_MATCH.MATCH_WINNER =1,IPL_MATCH.TEAM_ID1,IPL_MATCH.TEAM_ID2) as WINNING_TEAM_ID  FROM IPL_MATCH;

# BELOW CODE ONLY DISPLAY TEAM ID AND TEAM NAME OF MATCH WINNER 
select a.TEAM_ID as WINNING_TEAM_ID ,b.TEAM_NAME,a.WIN_DETAILS from 
(Select case when MATCH_WINNER='1' then TEAM_ID1 when MATCH_WINNER='2' then TEAM_ID2 end as TEAM_ID,WIN_DETAILS from IPL_MATCH) a
left join (select TEAM_ID,TEAM_NAME from IPL_TEAM) b on a.TEAM_ID = b.TEAM_ID;


-- 6.	Display total matches played, total matches won and total matches lost by team along with its team name.

SELECT IPL_TEAM_STANDINGS.TEAM_ID,IPL_TEAM.TEAM_NAME,SUM(IPL_TEAM_STANDINGS.MATCHES_WON) AS WON,
SUM(IPL_TEAM_STANDINGS.MATCHES_LOST) AS LOST from IPL_TEAM_STANDINGS JOIN IPL_TEAM ON IPL_TEAM_STANDINGS.TEAM_ID=IPL_TEAM.TEAM_ID
GROUP BY  IPL_TEAM_STANDINGS.TEAM_ID; -- 8 ROWS


-- 7.  Display the bowlers for Mumbai Indians team.

SELECT IPL_TEAM_PLAYERS.PLAYER_ID,IPL_PLAYER.PLAYER_NAME,IPL_TEAM_PLAYERS.PLAYER_ROLE,IPL_TEAM.TEAM_NAME
FROM IPL_TEAM_PLAYERS JOIN IPL_PLAYER ON IPL_TEAM_PLAYERS.PLAYER_ID=IPL_PLAYER.PLAYER_ID 
JOIN IPL_TEAM ON IPL_TEAM_PLAYERS.TEAM_ID=IPL_TEAM.TEAM_ID 
WHERE IPL_TEAM_PLAYERS.PLAYER_ROLE = 'BOWLER' and IPL_TEAM.TEAM_NAME='Mumbai Indians'; -- 9 rows

-- 8.	How many all-rounders are there in each team, Display the teams with more than 4 all-rounder in descending order.
SELECT IPL_TEAM.TEAM_NAME,COUNT(IPL_TEAM_PLAYERS.PLAYER_ROLE) AS COUNT
FROM IPL_TEAM_PLAYERS JOIN IPL_PLAYER ON IPL_TEAM_PLAYERS.PLAYER_ID=IPL_PLAYER.PLAYER_ID 
JOIN IPL_TEAM ON IPL_TEAM_PLAYERS.TEAM_ID=IPL_TEAM.TEAM_ID 
WHERE IPL_TEAM_PLAYERS.PLAYER_ROLE = 'ALL-ROUNDER' 
GROUP BY IPL_TEAM.TEAM_NAME HAVING COUNT > 4 ORDER BY COUNT DESC; -- 5 rows
